//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Entities.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurrentTransactionDetail
    {
        public int Id { get; set; }
        public Nullable<int> CurrentTransactionId { get; set; }
        public string ItemName { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
    
        public virtual CurrentTransaction CurrentTransaction { get; set; }
    }
}
