// <auto-generated />
namespace ERP.Entities.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class rmvtbl : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(rmvtbl));
        
        string IMigrationMetadata.Id
        {
            get { return "202104140523057_rmv-tbl"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
