// <auto-generated />
namespace ERP.Entities.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class tblcash : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tblcash));
        
        string IMigrationMetadata.Id
        {
            get { return "202104131302283_tbl-cash"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
